
services:
  weather-service:
    image: hnrkjnsn/testservice:latest
    build:
      context: ../TestService
      dockerfile: ../TestService/Dockerfile
    ports:
      - 5001:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_RESOURCE_ATTRIBUTES="service.name=resource-tutorial-dotnet,service.namespace=tutorial,service.version=1.0,service.instance.id=`uuidgen`,host.name=`HOSTNAME`,host.type=`uname -m`,os.name=`uname -s`,os.version=`uname -r`"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
